version: '3'
services:
  pyxtermjs:
    build: .
    image: crosslab/edrys_pyxtermjs_development:latest
    container_name: edrys_pyxtermjs_development
    ports:
      - "5000:5000"
    environment:
      - PYXTERM_CMD=zsh
